config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#homepage'


  get 'help/mobile', to: 'pages#help'
  #go to page controller and help action
  get 'plans/mobile-plans', to: 'plans#mobile'
  get 'tc', to: 'pages#tc'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def help
    @name = 'Sakshi'
  end
  def tc
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def mobile
  end
end

app/controllers/tc_controller.rb
class TcController < ApplicationController
  def tc
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/tc_helper.rb
module TcHelper
end

app/views/layouts/_cards.html.erb
<div class="container-fluid">

  <div class="card-deck">
    <div class="card c2">
      <img class="card-img-top" src="" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card c2">
      <img class="card-img-top" src="" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card c2">
      <img class="card-img-top" src="" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
  <div class="para2">
    <p><strong>If you own your phone and you're looking for a SIM you can rely on, amaysim is highly recommended.</strong></p>
  </div>
  <div class= "whistle">
    <p><strong>whistle<span class= "out">Out</span></strong></p>
  </div>

</div>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid color-fill" >
  <div class="container">
    <h1 class="display-3 text-white font"><strong>sim-only mobile plans</strong></h1>
    <p class="lead fontlead text-white" >Get UNLIMITED 2GB for $15 on your first 6 renewals.Use code 15FOR6 at checkout until 10th Sept. New customers only. Full T&Cs.</p>
    <div class="card-deck">
      <div class="card c1">
        <img class="card-img-top" src="" alt="Card image cap">
        <div class="card-block">
          <h4 class="card-title">Card title</h4>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card c1">
        <img class="card-img-top" src="" alt="Card image cap">
        <div class="card-block">
          <h4 class="card-title">Card title</h4>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card c1">
        <img class="card-img-top" src="" alt="Card image cap">
        <div class="card-block">
          <h4 class="card-title">Card title</h4>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card c1">
        <img class="card-img-top" src="" alt="Card image cap">
        <%#= image_tag("icon.png", size: "16x10", alt: "Edit Entry") %>
        <%= link_to "Go Home", root_path %>
        <div class="card-block">
          <h4 class="card-title">Card title</h4>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="siz">
    <p><strong>this is going to be amazing</strong></p>
  <div>
</div>

app/views/layouts/_jumbotron2.html.erb
<!-- <div class="jumbotron jumbotron-fluid bgcolor">
  <div class="container">
    <h1 class="display-3">buying in store?</h1>
    <p class="lead">Pick up a SIM at any one of our 12,000 retail stores and then pop online to choose and activate your plan.</p>
  </div>
</div> -->

<div class="jumbotron bgcolor">
  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/layouts/_jumbotronIndex.html.erb
<!-- <div class="jumbotron bg-purple">


  <div class="container bg-purple">
    <div class="row">
      <div class="col">
        <h6 class="">win a Google Home, Chromecast Ultra </h6>
        <p class="lead">and a year of nbn™</p>
        <hr class="my-4">
        <p>Sign up to any nbn plan before 31 August to go into the draw. Plans start from $40 a month.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">Sign up</a>
        </p>
      </div>
      <div class="col">
        <%= image_tag("house.png", height: '241', width: '345') %>
      </div>
    </div>
</div>
</div> -->

app/views/layouts/_nav.html.erb
<!-- # _ signifies partial -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item orange">
        <a class="nav-link" href="#">Activate SIM</a>
      </li>
      <li class="nav-item">
        <a class="nav-link orange" href="#">Login</a>
      </li>
    </ul>
  </div>
</nav>



<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  <div class="container">
  <a class="navbar-brand text-white" href="#">amaysim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          plans
        </a>
        <div class="dropdown-menu text-white" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          about
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li>
        <a class="nav-link text-white" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          help
        </a>
        <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div> -->
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amaysim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <a href="/help/mobile">Help</a> -->
    <!-- <%= link_to 'Help', help_mobile_path %> -->
    <!-- <%= link_to 'Help URL', help_mobile_path %> -->
<!-- <div class="container"> -->
    <%= render 'layouts/nav' %>
    <%#= render 'layouts/jumbotron' %>
    <%#= render 'layouts/cards' %>
    <%#= render 'layouts/jumbotron2' %>

      <%= yield %>
    <!-- </div> -->
  </body>
</html>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

<h1>
  <%= @name %>
</h1>

app/views/pages/homepage.html.erb
<div class= "bg-purple">
  <div class="container line">
    <div class="row text-white">
      <div class="col-sm-8">
      </br>
        <h1>win a Google Home, Chromecast Ultra and a year of nbn™</h1>

        <h6>Sign up to any nbn plan before 31 August to go into the draw. Plans start from $40 a month.</h6>
        <p>
          <a class="button text-white" href="#">sign up ></a>
      </div>
      <div class="col-sm-4">
        <%= image_tag("house.png", height: '241', width: '345') %>
      </div>
    </div>
  </div>
</div>

<div class="bg-white">
  <div class="container white-container">
    <div class="row">
      <div class="col-sm-4">
        <%= image_tag("img1.svg") %>
        <span class="nobr"><p><strong>no lock-in contracts</strong></p></span>
        <div class="para">
          <p>Freedom to switch your plan or cancel at anytime.</p>
        </div>
      </div>
      <div class="col-sm-4">
        <%= image_tag("img2.svg") %>
        <span class="nobr"><p><strong>simple to join</strong></p></span>
        <div class="para">
          <p>FQuick and easy online sign-up, we’ll take care of all the fiddly bits.</p>
        </div>
      </div>
      <div class="col-sm-4">
        <%= image_tag("img3.svg") %>
        <span class="nobr"><p><strong>easy to manage</strong></p></span>
        <div class="para">
          <p>Download our app or manage your plans online.</p>
        </div>
      </div>
    </div>


    <!-- <div class="row">
      <div class="col-sm-4"> -->
        <!-- <%= image_tag("mobile_plans") %> -->
        <!-- <div class="card">
          <div class="card-body">
            <p class="card-text"><strong>sim-only mobile plans<strong></p>
            <p>Unlimited standard talk text with heaps of data for use in Oz.</p>
          </div>
            <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout/public/cta/2017-05/nbn.png?itok=HQEt97oW," alt="Card image cap">
        </div>
      </div>
      <div class="col-sm-4"> -->
        <%#= image_tag("img2.svg") %>
      <!-- </div>
      <div class="col-sm-4"> -->
        <%#= image_tag("img3.svg") %>
      <!-- </div>
    </div> -->


  </div>
</div>

app/views/pages/tc.html.erb
<h1> you've made it to tc</h1>

app/views/plans/mobile.html.erb
<%= render 'layouts/jumbotron' %>
<%= render 'layouts/cards' %>
<%= render 'layouts/jumbotron2' %>